### PR TITLE
Charts

### PR DESCRIPTION
**Pull request by kahummer**
- [x] Add's donut charts to gisida-react

- [ ] Restructure charts directory structure

- [ ] Add doc's for this chart

- [ ] Add test for donut chart

### CODE REVIEW

**Comment by kahummer** [comment]
@ciremusyoka What's the status of this pr ?

**Comment by ciremusyoka** [comment]
> @ciremusyoka What's the status of this pr ?
@kahummer let me solve the conflicts and failing test then we merge

**Comment by cKellyDesign** [comment]
Looks like the only conflict is that we need to rerun `yarn build` to overwrite the conflicted `gisida-react.js`.

**Comment by cKellyDesign** [comment]
@kahummer @ciremusyoka What issues is this PR resolving? What are the changes being made? (Please add to description)

**Comment by ukanga** [comment]
@kahummer Do we usually include build/gisida_react.js in this repository? Is that not built during compilation and deployment?

**Comment by kahummer** [comment]
@ukanga we normally add the build for npm release purposes

**Comment by kelvin-muchiri** [comment]
@kahummer I think this found the file structure in reveal better where we have each component in its own folder with a `index.js(x)`. So that if tests were to be added and anything else related to that component such as documentation it can be in one place. For instance `src/lib/components/Charts/doughnutChart.jsx` becomes `src/lib/components/Charts/Doughnut/index.jsx`

**Review by kelvin-muchiri — COMMENTED** [review]
I was looking at [antd](https://github.com/ant-design/ant-design/tree/master/components) documentation some time back and realised we can borrow their documentation structure. We can have a documentation doc in each component. In our case here, can we add documentation for this component? @kahummer @ukanga what do you think?

**Comment by kahummer** [comment]
@kelvin-muchiri  yeah it is a good idea. That way  it's easier to narrow down into a specific component

**Pull request closed without merging**
